from __future__ import annotations

from typing import TypedDict


class SourceSpec(TypedDict):
    source_name: str
    source_type: str
    base_url: str
    priority: int
    expected_update_interval_minutes: int
    court_name: str
    court_level: str
    state: str
    parser_family: str


# Verified, official judiciary sources used for ingestion bootstrap and scraper wiring.
VERIFIED_INGESTION_SOURCES: list[SourceSpec] = [
    {
        "source_name": "njdg",
        "source_type": "API",
        "base_url": "https://njdg.ecourts.gov.in/",
        "priority": 1,
        "expected_update_interval_minutes": 1440,
        "court_name": "National Judicial Data Grid",
        "court_level": "national",
        "state": "National",
        "parser_family": "legacy",
    },
    {
        "source_name": "ecourts_services",
        "source_type": "SCRAPER",
        "base_url": "https://services.ecourts.gov.in/",
        "priority": 2,
        "expected_update_interval_minutes": 720,
        "court_name": "eCourts Services",
        "court_level": "district",
        "state": "National",
        "parser_family": "legacy",
    },
    {
        "source_name": "supreme_court_causelist",
        "source_type": "HTML",
        "base_url": "https://main.sci.gov.in/",
        "priority": 2,
        "expected_update_interval_minutes": 1440,
        "court_name": "Supreme Court of India",
        "court_level": "supreme",
        "state": "National",
        "parser_family": "legacy",
    },
    {
        "source_name": "high_court",
        "source_type": "HTML",
        "base_url": "https://www.allahabadhighcourt.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court",
        "court_level": "high",
        "state": "Unknown",
        "parser_family": "legacy",
    },
    {
        "source_name": "high_court_allahabad",
        "source_type": "HTML",
        "base_url": "https://www.allahabadhighcourt.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Allahabad High Court",
        "court_level": "high",
        "state": "Uttar Pradesh",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_andhra_pradesh",
        "source_type": "HTML",
        "base_url": "https://aphc.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court of Andhra Pradesh",
        "court_level": "high",
        "state": "Andhra Pradesh",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_bombay",
        "source_type": "HTML",
        "base_url": "https://bombayhighcourt.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Bombay High Court",
        "court_level": "high",
        "state": "Maharashtra",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_calcutta",
        "source_type": "HTML",
        "base_url": "https://www.calcuttahighcourt.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Calcutta High Court",
        "court_level": "high",
        "state": "West Bengal",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_chhattisgarh",
        "source_type": "HTML",
        "base_url": "https://highcourt.cg.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Chhattisgarh High Court",
        "court_level": "high",
        "state": "Chhattisgarh",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_delhi",
        "source_type": "HTML",
        "base_url": "https://delhihighcourt.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Delhi High Court",
        "court_level": "high",
        "state": "Delhi",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_gauhati",
        "source_type": "HTML",
        "base_url": "https://ghconline.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Gauhati High Court",
        "court_level": "high",
        "state": "Assam",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_gujarat",
        "source_type": "HTML",
        "base_url": "https://gujarathighcourt.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Gujarat High Court",
        "court_level": "high",
        "state": "Gujarat",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_himachal_pradesh",
        "source_type": "HTML",
        "base_url": "https://hphighcourt.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court of Himachal Pradesh",
        "court_level": "high",
        "state": "Himachal Pradesh",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_jammu_kashmir_ladakh",
        "source_type": "HTML",
        "base_url": "https://jkhighcourt.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court of Jammu & Kashmir and Ladakh",
        "court_level": "high",
        "state": "Jammu and Kashmir",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_jharkhand",
        "source_type": "HTML",
        "base_url": "https://jharkhandhighcourt.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Jharkhand High Court",
        "court_level": "high",
        "state": "Jharkhand",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_karnataka",
        "source_type": "HTML",
        "base_url": "https://karnatakajudiciary.kar.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Karnataka High Court",
        "court_level": "high",
        "state": "Karnataka",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_kerala",
        "source_type": "HTML",
        "base_url": "https://highcourtofkerala.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court of Kerala",
        "court_level": "high",
        "state": "Kerala",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_madras",
        "source_type": "HTML",
        "base_url": "https://www.hcmadras.tn.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Madras High Court",
        "court_level": "high",
        "state": "Tamil Nadu",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_madhya_pradesh",
        "source_type": "HTML",
        "base_url": "https://mphc.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court of Madhya Pradesh",
        "court_level": "high",
        "state": "Madhya Pradesh",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_manipur",
        "source_type": "HTML",
        "base_url": "https://hcmimphal.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Manipur High Court",
        "court_level": "high",
        "state": "Manipur",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_meghalaya",
        "source_type": "HTML",
        "base_url": "https://meghalayahighcourt.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court of Meghalaya",
        "court_level": "high",
        "state": "Meghalaya",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_odisha",
        "source_type": "HTML",
        "base_url": "https://orissahighcourt.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Orissa High Court",
        "court_level": "high",
        "state": "Odisha",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_patna",
        "source_type": "HTML",
        "base_url": "https://patnahighcourt.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Patna High Court",
        "court_level": "high",
        "state": "Bihar",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_punjab_haryana",
        "source_type": "HTML",
        "base_url": "https://highcourtchd.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Punjab and Haryana High Court",
        "court_level": "high",
        "state": "Chandigarh",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_rajasthan",
        "source_type": "HTML",
        "base_url": "https://hcraj.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Rajasthan High Court",
        "court_level": "high",
        "state": "Rajasthan",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_sikkim",
        "source_type": "HTML",
        "base_url": "https://hcs.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Sikkim High Court",
        "court_level": "high",
        "state": "Sikkim",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_telangana",
        "source_type": "HTML",
        "base_url": "https://tshc.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court for the State of Telangana",
        "court_level": "high",
        "state": "Telangana",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_tripura",
        "source_type": "HTML",
        "base_url": "https://thc.nic.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "Tripura High Court",
        "court_level": "high",
        "state": "Tripura",
        "parser_family": "generic_html",
    },
    {
        "source_name": "high_court_uttarakhand",
        "source_type": "HTML",
        "base_url": "https://highcourtofuttarakhand.gov.in/",
        "priority": 3,
        "expected_update_interval_minutes": 1440,
        "court_name": "High Court of Uttarakhand",
        "court_level": "high",
        "state": "Uttarakhand",
        "parser_family": "generic_html",
    },
    {
        "source_name": "tribunal_nclt",
        "source_type": "HTML",
        "base_url": "https://nclt.gov.in/",
        "priority": 4,
        "expected_update_interval_minutes": 1440,
        "court_name": "National Company Law Tribunal",
        "court_level": "tribunal",
        "state": "National",
        "parser_family": "generic_html",
    },
    {
        "source_name": "tribunal_nclat",
        "source_type": "HTML",
        "base_url": "https://nclat.nic.in/",
        "priority": 4,
        "expected_update_interval_minutes": 1440,
        "court_name": "National Company Law Appellate Tribunal",
        "court_level": "tribunal",
        "state": "National",
        "parser_family": "generic_html",
    },
    {
        "source_name": "tribunal_itat",
        "source_type": "HTML",
        "base_url": "https://itat.gov.in/",
        "priority": 4,
        "expected_update_interval_minutes": 1440,
        "court_name": "Income Tax Appellate Tribunal",
        "court_level": "tribunal",
        "state": "National",
        "parser_family": "generic_html",
    },
    {
        "source_name": "tribunal_cat",
        "source_type": "HTML",
        "base_url": "https://cgat.gov.in/",
        "priority": 4,
        "expected_update_interval_minutes": 1440,
        "court_name": "Central Administrative Tribunal",
        "court_level": "tribunal",
        "state": "National",
        "parser_family": "generic_html",
    },
]


GENERIC_HTML_SOURCE_SPECS: list[SourceSpec] = [
    spec for spec in VERIFIED_INGESTION_SOURCES if spec["parser_family"] == "generic_html"
]
