"""
RTI Export Module - PDF, Document, and Print Format Generation
RTI Act, 2005

Exports RTI requests in various formats suitable for printing,
digital submission, and official filing.
"""

from typing import Optional, Tuple, BinaryIO, Dict
from datetime import datetime
from io import BytesIO, StringIO
import textwrap


class RTIExportFormat:
    """Different export formats for RTI requests."""
    
    PDF = "pdf"
    DOCX = "docx"
    TXT = "txt"
    POSTAL = "postal"
    HTML = "html"


class RTIExporter:
    """Export RTI requests in multiple formats."""

    # =========================================================================
    # PLAINTEXT EXPORT
    # =========================================================================

    @staticmethod
    def export_as_text(
        rti_request_text: str,
        pio_address: str,
        applicant_name: str,
        case_number: str,
    ) -> str:
        """
        Export RTI as plain text with metadata headers.
        
        Args:
            rti_request_text: Generated RTI request text
            pio_address: PIO contact information
            applicant_name: RTI applicant name
            case_number: Case number for reference
            
        Returns:
            Formatted plain text document
        """
        header = f"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                         RTI REQUEST - PLAIN TEXT COPY                        ║
╚══════════════════════════════════════════════════════════════════════════════╝

APPLICANT:  {applicant_name}
CASE:       {case_number}
GENERATED:  {datetime.now().strftime('%d %B %Y at %H:%M:%S')}
FORMAT:     Plain Text (TXT)

PIO ADDRESS:
{pio_address}

════════════════════════════════════════════════════════════════════════════════

"""
        footer = f"""

════════════════════════════════════════════════════════════════════════════════
NOTES FOR SUBMISSION:

1. PRINT THIS DOCUMENT on standard A4 paper (210mm x 297mm)
2. SIGN AND DATE the document before sending
3. ATTACH documents listed as evidence
4. SEND BY REGISTERED POST with Acknowledgment Due, or hand-deliver
5. KEEP A COPY for your records
6. NOTE the exact date of submission for reference in appeals

EXPECTED PROCESSING:
- Standard Timeline: 30 days from receipt (as per Section 7, RTI Act 2005)
- Urgent cases: 48 hours (if applicable)
- You may receive a partial response if some information is exempt

If you don't receive acknowledgment within 5 days, follow up with PIO.

════════════════════════════════════════════════════════════════════════════════
Generated by Judiciary Accountability Initiative RTI Generator
Privacy Policy: No personal data is stored unless you explicitly save this document
════════════════════════════════════════════════════════════════════════════════
"""
        return header + rti_request_text + footer

    # =========================================================================
    # POSTAL FORMAT EXPORT
    # =========================================================================

    @staticmethod
    def export_as_postal_format(
        rti_request_text: str,
        pio_address: str,
        applicant_address: str,
        applicant_name: str,
        case_number: str,
    ) -> str:
        """
        Export RTI in postal/envelope format with address headers.
        
        Suitable for printing on envelopes or sending by registered mail.
        """
        # Format envelope address
        envelope_address = textwrap.dedent(f"""
        TO:
        {pio_address}
        """).strip()

        # Applicant return address
        return_address = textwrap.dedent(f"""
        FROM:
        {applicant_name}
        {applicant_address}
        """).strip()

        postal_document = f"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                    RTI REQUEST - POSTAL SUBMISSION FORMAT                    ║
╚══════════════════════════════════════════════════════════════════════════════╝

CASE REFERENCE: {case_number}
DATE: {datetime.now().strftime('%d %B %Y')}

--------------------------------------------------------------------------------
ENVELOPE ADDRESS (Copy to Envelope Front):
--------------------------------------------------------------------------------

{envelope_address}

--------------------------------------------------------------------------------
RETURN ADDRESS (Copy to Envelope Back/Top Left):
--------------------------------------------------------------------------------

{return_address}

--------------------------------------------------------------------------------
RTI REQUEST CONTENT:
--------------------------------------------------------------------------------

{rti_request_text}

--------------------------------------------------------------------------------
POSTAL SUBMISSION CHECKLIST:
--------------------------------------------------------------------------------

☐ Print this document on good quality A4 paper
☐ Sign and date the letter section
☐ Attach copies of:
  ☐ Case details/reference documents
  ☐ Identity proof (voter ID, Aadhar, Passport)
  ☐ Address proof (utility bill, lease agreement)

☐ Prepare envelope with addresses as shown above
☐ Include postal fee (as applicable)
☐ Send by "Registered Post with Acknowledgment Due" OR
  "Speed Post" for faster delivery
☐ Mark envelope with "RTI Request" in red ink
☐ Keep copy of RTI + postal receipt for records

RECOMMENDED SENDING METHODS:
1. India Post: Registered Post with Acknowledgment Due (Safest)
2. Speed Post: Faster but tracked differently
3. Hand Delivery: Get signed receipt from PIO office
4. Email (if addresses provided): Use with read receipt

TRACKING YOUR REQUEST:
- Note down the postal reference number from the receipt
- Track your letter on India Post website
- Once received, PIO will send acknowledgment (within 5 days)
- Keep all correspondence for appeal purposes

└─ Generated by Judiciary Accountability Initiative
"""
        return postal_document

    # =========================================================================
    # HTML EXPORT
    # =========================================================================

    @staticmethod
    def export_as_html(
        rti_request_text: str,
        pio_address: str,
        applicant_name: str,
        case_number: str,
    ) -> str:
        """
        Export RTI as HTML for web viewing and printing.
        """
        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RTI Request - {case_number}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
            padding: 20px;
        }}
        
        .container {{
            max-width: 900px;
            margin: 0 auto;
            background-color: white;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}
        
        .header {{
            text-align: center;
            border-bottom: 3px solid #1f4788;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }}
        
        .header h1 {{
            color: #1f4788;
            font-size: 24px;
            margin-bottom: 10px;
        }}
        
        .metadata {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin: 20px 0;
            padding: 15px;
            background-color: #f9f9f9;
            border-left: 4px solid #1f4788;
        }}
        
        .metadata-item {{
            display: flex;
            flex-direction: column;
        }}
        
        .metadata-label {{
            font-weight: bold;
            color: #1f4788;
            font-size: 12px;
            text-transform: uppercase;
            margin-bottom: 5px;
        }}
        
        .metadata-value {{
            font-size: 14px;
            color: #333;
        }}
        
        .pio-address {{
            background-color: #f0f7ff;
            border: 1px solid #1f4788;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        
        .pio-address h3 {{
            color: #1f4788;
            margin-bottom: 10px;
            font-size: 14px;
        }}
        
        .pio-address p {{
            font-size: 13px;
            line-height: 1.8;
            color: #333;
        }}
        
        .request-content {{
            margin: 30px 0;
            white-space: pre-wrap;
            word-wrap: break-word;
            font-family: 'Courier New', monospace;
            background-color: #ffffff;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 4px;
            line-height: 1.6;
        }}
        
        .footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
            text-align: center;
        }}
        
        .submission-checklist {{
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 20px;
            margin: 20px 0;
            border-radius: 4px;
        }}
        
        .submission-checklist h3 {{
            color: #856404;
            margin-bottom: 10px;
        }}
        
        .submission-checklist ul {{
            margin-left: 20px;
        }}
        
        .submission-checklist li {{
            margin-bottom: 8px;
            color: #333;
        }}
        
        @media print {{
            body {{
                background-color: white;
                padding: 0;
            }}
            
            .container {{
                box-shadow: none;
                max-width: 100%;
            }}
            
            .no-print {{
                display: none;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>RTI REQUEST</h1>
            <p>Right to Information Act, 2005</p>
        </div>
        
        <div class="metadata">
            <div class="metadata-item">
                <span class="metadata-label">Applicant</span>
                <span class="metadata-value">{applicant_name}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">Case Number</span>
                <span class="metadata-value">{case_number}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">Generated</span>
                <span class="metadata-value">{datetime.now().strftime('%d %B %Y')}</span>
            </div>
            <div class="metadata-item">
                <span class="metadata-label">Format</span>
                <span class="metadata-value">HTML/Web</span>
            </div>
        </div>
        
        <div class="pio-address">
            <h3>To: Public Information Officer</h3>
            <p>{pio_address.replace(chr(10), '<br>')}</p>
        </div>
        
        <div class="request-content">
{rti_request_text}
        </div>
        
        <div class="submission-checklist">
            <h3>Submission Guidelines</h3>
            <ul>
                <li>Print this document on standard A4 paper</li>
                <li>Sign and date the document</li>
                <li>Attach supporting documents (case details, ID proof)</li>
                <li>Send by Registered Post (Acknowledgment Due) or hand-deliver</li>
                <li>Keep a copy for your records</li>
                <li>Note the submission date for appeal reference</li>
            </ul>
        </div>
        
        <div class="footer">
            <p>Generated using Judiciary Accountability Initiative - RTI Generator</p>
            <p>No personal data is stored unless you explicitly save this document.</p>
            <p>For assistance: <a href="https://judiciaryaccountability.org">judiciaryaccountability.org</a></p>
        </div>
    </div>
</body>
</html>"""
        return html_content

    # =========================================================================
    # MARKDOWN EXPORT
    # =========================================================================

    @staticmethod
    def export_as_markdown(
        rti_request_text: str,
        pio_address: str,
        applicant_name: str,
        case_number: str,
    ) -> str:
        """
        Export RTI as Markdown for documentation and version control.
        """
        markdown_content = f"""# RTI Request

**Case:** {case_number}  
**Applicant:** {applicant_name}  
**Generated:** {datetime.now().strftime('%d %B %Y')}  

---

## To: Public Information Officer

```
{pio_address}
```

---

## Request

{rti_request_text}

---

## Submission Notes

- [ ] Print on A4 paper
- [ ] Sign and date
- [ ] Attach supporting documents
- [ ] Send by registered post or hand-deliver
- [ ] Keep a copy for records
- [ ] Note submission date

---

*Generated by Judiciary Accountability Initiative RTI Generator*
"""
        return markdown_content

    # =========================================================================
    # EXPORT COORDINATION
    # =========================================================================

    @staticmethod
    def export_rti_request(
        rti_request_text: str,
        pio_address: str,
        applicant_name: str,
        case_number: str,
        export_format: str = RTIExportFormat.TXT,
    ) -> Tuple[bool, str]:
        """
        Unified export function for different formats.
        
        Args:
            rti_request_text: Generated RTI text
            pio_address: PIO address
            applicant_name: Applicant name
            case_number: Case reference number
            export_format: Format (txt, html, markdown, postal)
            
        Returns:
            (success, exported_content)
        """
        try:
            if export_format == RTIExportFormat.TXT:
                content = RTIExporter.export_as_text(
                    rti_request_text, pio_address, applicant_name, case_number
                )
            
            elif export_format == RTIExportFormat.HTML:
                content = RTIExporter.export_as_html(
                    rti_request_text, pio_address, applicant_name, case_number
                )
            
            elif export_format == RTIExportFormat.POSTAL:
                content = RTIExporter.export_as_postal_format(
                    rti_request_text, pio_address,
                    "[Your Full Address]",
                    applicant_name, case_number
                )
            
            elif export_format == "markdown":
                content = RTIExporter.export_as_markdown(
                    rti_request_text, pio_address, applicant_name, case_number
                )
            
            else:
                return False, f"Unsupported format: {export_format}"
            
            return True, content
        
        except Exception as e:
            return False, f"Export error: {str(e)}"

    @staticmethod
    def get_supported_formats() -> List[Dict]:
        """List all supported export formats with descriptions."""
        return [
            {
                "format": RTIExportFormat.TXT,
                "name": "Plain Text",
                "extension": ".txt",
                "description": "Plain text file suitable for email or printing",
                "use_case": "General submission via email or printing"
            },
            {
                "format": RTIExportFormat.HTML,
                "name": "Web/HTML",
                "extension": ".html",
                "description": "Formatted HTML for web viewing and printing",
                "use_case": "View in browser, professional printing"
            },
            {
                "format": RTIExportFormat.POSTAL,
                "name": "Postal Format",
                "extension": ".txt",
                "description": "Ready for postal submission with envelope format",
                "use_case": "Registered mail submission"
            },
            {
                "format": "markdown",
                "name": "Markdown",
                "extension": ".md",
                "description": "Markdown format for documentation",
                "use_case": "Repository storage, version control"
            },
        ]
